---
  apiVersion: "apps/v1"
  kind: "Deployment"
  metadata: 
    name: "uptime-test"
    namespace: "default"
    labels: 
      app: "uptime-test"
  spec:
    replicas: 3
    selector:
      matchLabels:
        app: "uptime-test"
    template:
      metadata:
        labels:
          app: "uptime-test"
      spec:
        containers: 
        - name: "uptime-test-pod"
          image: "guisousa/uptime:3.1"
          ports:
          - containerPort: 3001
            protocol: TCP