---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: uptime-pv
  labels:
    app: uptime-test
spec:
  storageClassName: uptime-host-pv
  capacity:
    storage: 30Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/uptime/data"
