---
apiVersion: "v1"
kind: PersistentVolumeClaim
metadata:
  name: uptime-pvc
  labels:
    app: uptime-test
spec:
  storageClassName: uptime-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi
