---
  apiVersion: "v1"
  kind: "Service"
  metadata:
    name: "uptime-lb"
    namespace: "default"
    labels:
      app: "uptime-test"
  spec:
    ports:
    - protocol: "TCP"
      port: 80
      targetPort: 3001
    selector:
      app: "uptime-test"
    type: "LoadBalancer"
    loadBalancerIP: ""